### ISSUE TITLE
Version 2.4.1 cannot work with elasticsearch 1.4.4

### ISSUE THREAD

**Issue by jeffreyji666** [elasticsearch/elasticsearch-cloud-aws#185]
I installed cloud-aws plugin for elasticsearch 1.4.4 on aws cloud ec2, but cannot boot the elasticsearch. 

and I got this error:
xxxx:/usr/local/elasticsearch/plugins/cloud-aws$ sudo service elasticsearch start
PID file found in /usr/local/var/run/ip_xxx_compute_internal.pid
Starting Elasticsearch...[2015-03-02 10:22:36,211][INFO ][node                     ] [ip-172-31-4-252.cn-north-1.compute.internal] version[1.4.4], pid[32638], build[c88f77f/2015-02-19T13:05:36Z]
[2015-03-02 10:22:36,211][INFO ][node                     ] [ip-172-31-4-252.cn-north-1.compute.internal] initializing ...
[2015-03-02 10:22:36,258][INFO ][plugins                  ] [ip-172-31-4-252.cn-north-1.compute.internal] loaded [cloud-gce, analysis-ansj, cloud-aws], sites [head, paramedic]
{1.4.4}: Initialization Failed ...
1) NoSuchMethodError[org.apache.http.conn.scheme.Scheme.<init>(Ljava/lang/String;ILorg/apache/http/conn/scheme/SchemeSocketFactory;)V]2) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]
 [OK]

google it and it suggests I should upgrade httpclient jar file, still doesn't work.

**Comment by dadoonet** [comment]
Indeed. This region is not defined in 2.4.1 but 2.4.2. See https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/156#issuecomment-75073370

I think it's the cause here but could you paste the full logs?

**Comment by jeffreyji666** [comment]
my cloud-aws version is: 2.4.1.

could you please tell me how to install version 2.4.2? I try to install it by:  cd $ES_HOME; bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.2

but I cannot install it successfully.

**Comment by dadoonet** [comment]
It has not been released yet.
If you need it now, you need to build a SNAPSHOT with maven.

**Comment by jeffreyji666** [comment]
I build a 3.0.0-SNAPSHOT edition from the master branch, but got this error:

root@ip-172-31-6-183:~/elasticsearch-1.4.4# bin/elasticsearch
[2015-03-03 14:33:17,774][INFO ][node                     ] [Hector] version[1.4.4], pid[2000], build[c88f77f/2015-02-19T13:05:36Z]
[2015-03-03 14:33:17,775][INFO ][node                     ] [Hector] initializing ...
[2015-03-03 14:33:17,802][INFO ][plugins                  ] [Hector] loaded [cloud-aws], sites []
{1.4.4}: Initialization Failed ...
1) NoSuchMethodError[org.elasticsearch.common.settings.SettingsFilter.addFilter(Ljava/lang/String;)V]2) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]

**Comment by dadoonet** [comment]
You need to build it from es-1.4 branch.

**Comment by jeffreyji666** [comment]
still doesn't work, I use the unicast to solve the problem.

**Comment by dadoonet** [comment]
That's why I asked for:

> but could you paste the full logs?

Any chance you can share this?

**Comment by jeffreyji666** [comment]
now 2.4.2-SNAPSHOT is ok, but I got jackson error yesterday, and the error doesn't happen again.

but I still need to use unicast instead of cloud-aws for I use chef to deploy the es cluster, and chef cannot download cloud-aws 2.4.2-SNAPSHOT currently.

**Comment by dadoonet** [comment]
If I understand correctly, we can close this issue as it is fixed in 2.4.2.
Feel free to reopen if it's not the case.

**Comment by jeffreyji666** [comment]
yep. thank you very much.

**Comment by frederic-jomedia** [comment]
any idea when 2.4.2 will be out of snapshot ?
Tx

**Comment by jeffreyji666** [comment]
2.4.2 is good. you can use it.

**Comment by dadoonet** [comment]
@frederic-jomedia I agree. We need to release 2.4.2.
